In [12]:
import numpy as np
# 1.Create an array of 10 zeros
a=np.zeros(10, dtype = 'int16')
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [18]:
# 2.Create an array of 10 ones
a=np.ones(10, dtype = 'int16')
print(a)

[1 1 1 1 1 1 1 1 1 1]


In [23]:
#3. Create an array of 10 fives
a=np.full(10,5)
print(a)

[5 5 5 5 5 5 5 5 5 5]
