In [4]:
import numpy as np

#### 1. Write a NumPy program to get the numpy version and show numpy build configuration.

In [12]:
np.version.version

'1.26.4'

In [16]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/DAI.STUDENTSDC/AppData/Local/anaconda3/Library/include
    lib directory: C:/Users/DAI.STUDENTSDC/AppData/Local/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family

#### 2. Write a NumPy program to get help on the add function.

In [46]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

In [20]:
# other method to do the same is
np.add?

Signature:       np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\dai.studentsdc\appdata\local\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    

#### 3. Write a NumPy program to test whether none of the elements of a given array is zero.

In [39]:
a = np.array([1,2,3,4,5,67,41,3,54,56])
b = "No_zero" if all(a!=0) else "Zero is present"
print(b)

No_zero


#### 4.Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [83]:
# s = [int(x) for x in input("Enter the integer values you want to store in array:").split()]
a = np.array([1,2,3,4,5,67,41,3,54,56])
b = "Non_zero is present" if all(a!=0) else "Zero is present"
print(b)


Non_zero is present


#### 5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [108]:
a = np.array([1,2,3,4,5,67,41,np.nan,54,56])
np.isfinite(a)

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True])

#### 6. Write a NumPy program to test element-wise for positive or negative infinity.

In [112]:
a = np.array([1,np.inf,3,4,5,67,41,np.nan,54,56])
[print("+/- infinity") if x else print("Not +/- infinity") for x in np.isinf(a)]
np.isinf(a)

Not +/- infinity
+/- infinity
Not +/- infinity
Not +/- infinity
Not +/- infinity
Not +/- infinity
Not +/- infinity
Not +/- infinity
Not +/- infinity
Not +/- infinity


array([False,  True, False, False, False, False, False, False, False,
       False])

#### 7. Write a NumPy program to test element-wise for NaN of a given array.

In [115]:
a = np.array([1,np.inf,3,4,5,67,41,np.nan,54,56])
np.isnan(a)

array([False, False, False, False, False, False, False,  True, False,
       False])

#### 8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [152]:
a = np.array([1,np.inf,3,4,5,67,41,np.nan,54,56+8j])
print("Checking weather element is complex or not--------->\n.", np.iscomplex(a))
print("Checking weather element is scaler or not--------->\n.", np.isscalar(a))
print("Checking weather element is real or not--------->\n.", np.isreal(a))

Checking weather element is complex or not--------->
. [False False False False False False False False False  True]
Checking weather element is scaler or not--------->
. False
Checking weather element is real or not--------->
. [ True  True  True  True  True  True  True  True  True False]


#### 9. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and 
less_equal) of two given arrays.

In [178]:
a = np.array([1,2,3,4,5,67,41,3,54,56])
b=np.array([10,2,1,5,76,84,564,6,3,2])
print("Checking weather element of array a is greater than or not--------->\n.", a>b)
print("\nChecking weather element of array a is greater than equal to or not--------->\n.", a>=b)
print("\nChecking weather element of array a is less than or not--------->\n.", a<b)
print("\nChecking weather element of array a is less than equal to or not--------->\n.", a<=b)


Checking weather element of array a is greater than or not--------->
. [False False  True False False False False False  True  True]

Checking weather element of array a is greater than equal to or not--------->
. [False  True  True False False False False False  True  True]

Checking weather element of array a is less than or not--------->
. [ True False False  True  True  True  True  True False False]

Checking weather element of array a is less than equal to or not--------->
. [ True  True False  True  True  True  True  True False False]


#### 10 Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the 
memory occupied by the array.

In [200]:
a=np.array([1,7,13,105])
print(a.size*a.itemsize,"Bytes")

16 Bytes


#### 11. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [212]:
a=np.zeros(10, dtype = 'int16')
print("Array of 10 zeros:",a)
a=np.ones(10, dtype = 'int16')
print("Array of 10 ones: ",a)
a=np.full(10,5)
print("Array of 10 fives:",a)

Array of 10 zeros: [0 0 0 0 0 0 0 0 0 0]
Array of 10 ones:  [1 1 1 1 1 1 1 1 1 1]
Array of 10 fives: [5 5 5 5 5 5 5 5 5 5]


#### 12. Write a NumPy program to create an array of the integers from 30 to70.

In [224]:
print(np.arange(30,71))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


#### 13 Write a NumPy program to create an array of all the even integers from 30 to 70.

In [227]:
print(np.arange(30,71,2))

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#### 14. Write a NumPy program to create a 3x3 identity matrix.

In [251]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 15. Write a NumPy program to generate a random number between 0 and 1.

In [254]:
np.random.rand()

0.8363237384684722

#### 16. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [257]:
np.random.randn(15)

array([ 1.50317406, -0.86063396,  0.96617687, -0.69022235, -1.03661876,
       -0.35745717,  1.33848918, -0.29488878, -1.45292161, -0.16532356,
       -0.78310612,  0.56525147,  0.65317363,  0.43363533, -0.40437657])

#### 17. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [278]:
a=np.random.randint(15,55,10)
print(a, "\n" ,  a[1:-1])

[54 32 21 24 47 16 48 46 22 45] 
 [32 21 24 47 16 48 46 22]


#### 18. Write a NumPy program to create a 3X4 array.

In [316]:
print(np.empty((3,4)))

[[0.88380034 0.13480137 0.35084005 0.38052184]
 [0.04734111 0.10165901 0.26998811 0.21938839]
 [0.12023903 0.73622957 0.47795686 0.67423806]]


#### 19. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [302]:
np.linspace(5,50,10, dtype=int)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

#### 20. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [327]:
a=np.arange(0,21)
a[9:16]= -a[9:16]
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

#### 21. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [338]:
a=np.random.randint(0,10,5)
print(a)

[9 5 8 8 5]


#### 22. Write a NumPy program to multiply the values of two given vectors.

In [345]:
a=np.array([1,2,3,4])
b=np.array([5,4,3,2])
print("The product of each element of the arrays a and b :\n",a*b)

The product of each element of the arrays a and b :
 [5 8 9 8]


#### 23. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

In [348]:
np.random.randint(10,22,(3,4))

array([[12, 15, 21, 10],
       [21, 14, 13, 19],
       [20, 16, 19, 16]])

#### 24. Write a NumPy program to find the number of rows and columns of a given matrix.

In [361]:
a=np.array([[1,4,6,8,3],[2,4,5,6,7]])
a.shape

(2, 5)

#### 25. Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.

In [364]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 26. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [391]:
a=np.zeros((10,10))
a[0], a[-1], a[:,0], a[:,-1]  = 1,1,1,1

In [419]:
a

array([[[0.35438709, 0.91868105, 0.54401524],
        [0.85124646, 0.66591182, 0.60211268],
        [0.07910617, 0.34698651, 0.17619567]],

       [[0.42055762, 0.34029888, 0.0249727 ],
        [0.11343401, 0.40766985, 0.9857122 ],
        [0.30403444, 0.0609002 , 0.00170374]],

       [[0.09297278, 0.72155545, 0.02319815],
        [0.68990229, 0.20136959, 0.73886927],
        [0.57624407, 0.33141478, 0.5256488 ]]])

#### 27. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [397]:
a=np.zeros((5,5))
for i in range(5):
    a[i,i]=i+1
print(a)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


#### 28. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

In [417]:
a=np.random.rand(3,3,3)
print(a)

[[[0.35438709 0.91868105 0.54401524]
  [0.85124646 0.66591182 0.60211268]
  [0.07910617 0.34698651 0.17619567]]

 [[0.42055762 0.34029888 0.0249727 ]
  [0.11343401 0.40766985 0.9857122 ]
  [0.30403444 0.0609002  0.00170374]]

 [[0.09297278 0.72155545 0.02319815]
  [0.68990229 0.20136959 0.73886927]
  [0.57624407 0.33141478 0.5256488 ]]]


#### 29. Write a NumPy program to compute the inner product of two given vectors.

In [452]:
a = np.random.randint(1,13,(3,3))
b = np.random.randint(1,22,(3,3))
print("Matrix a:\n", a, "\nMatrix b:\n", b, "\n dot product of them is:\n",a.dot(b))

Matrix a:
 [[12  2 10]
 [ 4 12  6]
 [11 11  3]] 
Matrix b:
 [[11 10  2]
 [ 4  5 21]
 [20  8  8]] 
 dot product of them is:
 [[340 210 146]
 [212 148 308]
 [225 189 277]]


#### 30. Write a NumPy program to sort a given array by row and column in ascending order.

In [455]:
a

array([[12,  2, 10],
       [ 4, 12,  6],
       [11, 11,  3]])

In [457]:
a.sort(axis = 1)
print("sorted row wise:\n", a)

sorted row wise:
 [[ 2 10 12]
 [ 4  6 12]
 [ 3 11 11]]


In [459]:
a.sort(axis = 0)
print("sorted coloumn wise:\n", a)

sorted coloumn wise:
 [[ 2  6 11]
 [ 3 10 12]
 [ 4 11 12]]


#### 31. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

In [494]:
a = np.random.randint(1,187,12)
print("Given array:\n",a)
print("elements from vector a which are less than 50 and greater than 10 are:", a[(a>10) & (a < 50)])

Given array:
 [ 34 132 178   7  44  89 114  84 170 119 162 165]
elements from vector a which are less than 50 and greater than 10 are: [34 44]


#### 32. Write a NumPy program to replace all numbers in a given array which is equal, less and greater to a given number.

In [509]:
a = np.array([1,2,3,4,5,5,5,5,3,2,7,8,9,7,8,56,56,4,678])
a[a==5] = 69
print("Number equal to 5 are replaced by 69 :",a)

a = np.array([1,2,3,4,5,5,5,5,3,2,7,8,9,7,8,56,56,4,678])
a[a>5] = 6
print("Number greater than 5 are replaced by 6 :",a)

a = np.array([1,2,3,4,5,5,5,5,3,2,7,8,9,7,8,56,56,4,678])
a[a<5] = 4
print("Number less than 5 are replaced by 4 :",a)

Number equal to 5 are replaced by 69 : [  1   2   3   4  69  69  69  69   3   2   7   8   9   7   8  56  56   4
 678]
Number greater than 5 are replaced by 6 : [1 2 3 4 5 5 5 5 3 2 6 6 6 6 6 6 6 4 6]
Number less than 5 are replaced by 4 : [  4   4   4   4   5   5   5   5   4   4   7   8   9   7   8  56  56   4
 678]


#### 33. Write a NumPy program to create an array of equal shape and data type of a given array.

In [556]:
a=np.array([1,2,3,4,5.6,6])
b=np.empty_like(a)
b

array([1. , 2. , 3. , 4. , 5.6, 6. ])

#### 34. Write a NumPy program to create a three-dimension array with shape (3,5,4) and set to a variable.

In [567]:
np.full((3,5,4),3)
np.random.rand(3,4,5)                                                                                                      

array([[[0.71871972, 0.78332594, 0.40117096, 0.94366889, 0.43907768],
        [0.34150826, 0.42839528, 0.02517997, 0.46552571, 0.46684399],
        [0.73862203, 0.08682607, 0.41093539, 0.37733296, 0.47586011],
        [0.64014972, 0.94656789, 0.89512424, 0.95322101, 0.33251945]],

       [[0.99220756, 0.91734935, 0.49582735, 0.23483598, 0.38026138],
        [0.79679424, 0.62377318, 0.77820863, 0.81303467, 0.47768776],
        [0.40431364, 0.67063509, 0.60897639, 0.15678433, 0.73083123],
        [0.50082792, 0.82167129, 0.1352256 , 0.79208092, 0.79751572]],

       [[0.90319127, 0.140301  , 0.72164871, 0.69868999, 0.93969897],
        [0.35828619, 0.85790435, 0.05158794, 0.73570893, 0.45220535],
        [0.39607819, 0.6108236 , 0.58361803, 0.1910511 , 0.66791528],
        [0.83705483, 0.67473906, 0.42007834, 0.00789446, 0.93441378]]])

#### 35. Write a NumPy program to multiply two given arrays of same size element-by-element.

In [573]:
a=np.array([1,2,4,6,7])
b=np.array([7,5,8,3,1])
a*b

array([ 7, 10, 32, 18,  7])

In [577]:
a = [1,2,3,4,56,7,7,3,2,-2,-2,2-1,-1,3,-3,4]
b = [x for x in a if x < 0]

In [579]:
b

[-2, -2, -1, -3]