# NumPy

In [2]:
import numpy as np
my_list=[1,2,3]
my_array=np.array([1,2,3])

In [4]:
print(type(my_list))

<class 'list'>


In [6]:
print(np.array(my_list))

[1 2 3]


In [8]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
print(np.array(my_matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
#start,stop,step
print(np.arange(0,10))
print(np.arange(0,11,2))

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]


In [26]:
print(np.zeros(3))
print(np.zeros((5,5)))
print(np.ones(3))
print(np.ones((3,3)))

[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
#start, stop, number of elements(and not stop as in the case of arange)
print(np.linspace(0,10,3))
print(np.linspace(0,5,20))
print(np.linspace(0,5,21))

[ 0.  5. 10.]
[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25
 3.5  3.75 4.   4.25 4.5  4.75 5.  ]


## Random
 - Random number arrays b/w 0 and 1 random.rand


In [30]:
print(np.random.rand(2))
print(np.random.rand(5,5))      

[0.59684982 0.35009286]
[[0.62808407 0.55494498 0.70718841 0.42158289 0.6142331 ]
 [0.52059888 0.51344453 0.58560984 0.12179301 0.43933828]
 [0.93882751 0.91545806 0.31465911 0.78425821 0.18927667]
 [0.98667913 0.60052827 0.54001232 0.47380595 0.5114757 ]
 [0.13781943 0.71337056 0.30205823 0.90519141 0.79598498]]


- normal distribution

In [72]:
print(np.random.randn(2)) #2 random number from normal distribution
print(np.random.randn(5,5))

[0.30588972 1.16394216]
[[-1.04909539 -0.97657801 -0.63905079  1.69742923 -1.2861153 ]
 [-0.18916158 -0.07391267 -0.16049537 -0.10879348 -0.69698401]
 [-1.00581081 -0.39254505 -2.1377931   1.76093089 -0.77419323]
 [-0.53023393 -0.79351601  0.29190243 -1.22200536 -1.56903777]
 [ 0.39995016 -0.04564469 -0.91591943  1.11898648  0.19738121]]



- to print random integer within specified range we can use
- random.randint(Start, End)
- End will not be included


print(np.random.randint(1,100)) #Single random integers between 1 and 100
print(np.random.randint(1,100,10)) # 10 random integers between 1 and 100

#### to make the random same
- we can use **np.random.seed(77)**
- if in two system same seed is used same random element will be generated
- 

In [56]:
#Seeding for reproducable results
np.random.seed(77)
print(np.random.rand(4))

[0.91910903 0.6421956  0.75371223 0.13931457]


In [60]:
#Storing
arr=np.arange(25) #numbers from 0 to 24
ranarr=np.random.randint(0,50,10) #10 random numbers b/w 0 and 50
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[32 39 44 19 32 36 36 47 14 15]


In [62]:
#reshape: Returns an array containing the same data with a new shape
print(arr.reshape(5,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


- print(ranarr.argmax()) # to find index of the max

In [67]:
#Max, min and their index positons
print(ranarr.max())
print(ranarr.argmax()) # to find index of the max
print(ranarr.min())


47
7
14


## indexing

In [ ]:
# get a 
print(arr[8])

In [76]:
arr=np.arange(0,11)

In [80]:
#Slicing
slice_of_arr=arr[0:6]
print(slice_of_arr)

[0 1 2 3 4 5]


In [82]:
#Change Slice
slice_of_arr[:]=99  #changes made are also there in our original array!
print(slice_of_arr) #Data is not copied, it it a view of the original array!
print(arr) #This avoid memory problems as both are pointing to the same are of meomory.


[99 99 99 99 99 99]
[99 99 99 99 99 99  6  7  8  9 10]


###### To get a copy, we need to be explicit about it.**arr.copy()**

In [84]:
#To get a copy, we need to be explicit
arr_copy=arr.copy()
print(arr_copy)

[99 99 99 99 99 99  6  7  8  9 10]


In [88]:
#Conditional selection
arr=np.arange(1,11)

In [90]:
#check each element of the array >4 and returns a BOOLEAN array
print(arr>4)

[False False False False  True  True  True  True  True  True]


In [94]:
#Select only those elements from the arr array where it is TRUE
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [179]:
#basic arithmetic
print(arr+arr)
print(arr-arr)
print(arr*arr)

[ 2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0]
[  1   4   9  16  25  36  49  64  81 100]


In [185]:
#This will raise a Warning on division by zero, but not an error!
print(arr/arr) #It just fills the spot with nan 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [187]:
#Also a warning (but not an error) relating to infinity
print(1/arr)

[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111 0.1       ]


In [191]:
print(arr**3) #exponent

[   1    8   27   64  125  216  343  512  729 1000]


In [205]:
#Universal functions
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


In [209]:
#Summary statistics
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.var())
print(arr.std())

55
5.5
10
1
8.25
2.8722813232690143


In [211]:
#2D arrays
arr_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) #2-d array with 3 rows and 4 columns
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [215]:
#Row and column count
print(arr_2d.shape)  #shape is a property and not a function so don't use brackets after shape
#Sum all the columns for each row(e.g 1+5+9, 2+6+10, etc.)
print(arr_2d.sum(axis=0))
#Sum all the rows for each column(e.g 1+2+3+4, 5+6+7+8, etc.)
print(arr_2d.sum(axis=1))

(3, 4)
[15 18 21 24]
[10 26 42]


In [223]:
# 1.creating an array of 10 zeros
np.zeros(10, dtype = 'int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [225]:
np.ones(10, dtype = 'int16')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [245]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [259]:
a = np.arange(10,51)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [261]:
a[a%2 == 0]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [263]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [265]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [269]:
np.random.rand()

0.5491466098240255

In [273]:
np.random.randn(25)

array([ 0.27506011, -0.18398014, -0.87868479,  0.67858291, -0.46843454,
       -0.44852893,  0.01340295,  0.62979163, -0.52423517,  0.7723438 ,
       -0.6653281 , -1.5662735 ,  0.0648559 , -0.01317517,  0.93234945,
       -1.49989509,  0.21757692, -0.3347531 ,  0.09673975, -2.29244733,
       -0.76124004, -0.04993861,  1.84723938, -1.16954466, -2.38300287])

In [271]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

#### use `np.eye()` when you need flexibility in the dimensions of the matrix, and use `np.identity()` otherwiswe

## np.where(...):

This function from the NumPy library is used to get the indices of the True values in the Boolean Series.

### pandas.DataFrame.ne
- DataFrame.ne(other, axis='columns', level=None)
- Get Not equal to of dataframe and other, element-wise (binary operator ne).

Among flexible wrappers (eq, ne, le, lt, ge, gt) to comparison operators.

Equivalent to ==, !=, <=, <, >=, > with support to choose axis (rows or columns) and level for comparison.